/*
 * include/asm-arm/arch-comcerto/comcerto-300.h
 *
 * Copyright (C) 2010 Mindspeed Technologies, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef __ASM_ARCH_COMCERTO_300_H
#define __ASM_ARCH_COMCERTO_300_H


/*
 * ========================================================================
 *  Comcerto definitions
 * ========================================================================
 *
 */

#define COMCERTO_IBR_CS2_REMAP_BASE	0xB8000000	/* base address of flash when booted via IBR */

#define COMCERTO_UEXP_DA_BASE		0x7FF00000

#define COMCERTO_CS5_BASE		0x11C00000
#define COMCERTO_CS4_BASE		0x11800000
#define COMCERTO_CS3_BASE		0x11400000
#define COMCERTO_CS2_BASE		0x11000000

#define COMCERTO_GEMAC1_BASE		0x10170000
#define COMCERTO_ARBITER_CPRAM_BASE	0x10108000
#define COMCERTO_ARBITER_ERAM_BASE	0x10100000
#define COMCERTO_MEMCORE_BASE		0x100F0000
#define COMCERTO_EDMA_GEMAC1_BASE	0x100E0700
#define COMCERTO_EDMA_GEMAC0_BASE	0x100E0100
#define COMCERTO_IDMA_BASE		0x100E0000
#define COMCERTO_GEMAC0_BASE		0x100D0000
#define COMCERTO_NTG_BASE		0x100B8000
#define COMCERTO_PLL_BASE		0x100B0000
#define COMCERTO_INTC_BASE		0x100A0000
#define COMCERTO_I2C_CTRLADDR		0x1009D000
#define COMCERTO_I2C_BASE		0x1009C000
#define COMCERTO_SPI1_BASE		0x1009A000
#define COMCERTO_SPI0_BASE		0x10098000
#define COMCERTO_UART1_BASE		0x10094000
#define COMCERTO_UART0_BASE		0x10090000
#define COMCERTO_SDC_BASE		0x10080000
#define COMCERTO_GPIO_BASE		0x10070000
#define COMCERTO_DECODER_BASE		0x10060000
#define COMCERTO_TIMER_BASE		0x10050000
#define COMCERTO_ARBITER_ARAM_BASE	0x10048000
#define COMCERTO_ARBITER_BASE		0x10040000
#define COMCERTO_TDMA_BASE		0x10020000
#define COMCERTO_PHI_BASE		0x10010000

#ifndef CONFIG_ARCH_M823V2
#define COMCERTO_SERDES_BASE		0x101A0000
#define COMCERTO_SPU1_BASE		0x10120000
#define COMCERTO_PUI_BASE		0x100C0000
#endif

#define APB_MEMORY_PHY			0x10000000
#define ARAM_MEMORY_PHY			0x0A000000
#define ERAM_MEMORY_PHY			0x08000000
#define SDRAM_MSP_MEMORY_PHY		0x00000000

#define APB_MEMORY_VADDR		0xE8000000
#define ARAM_MEMORY_VADDR		0xFA000000
#define ERAM_MEMORY_VADDR		0xF8000000
#define SDRAM_MSP_MEMORY_VADDR		0xF0000000

#define APB_MEMORY_SIZE			(16*1024*1024)
#define ARAM_MEMORY_SIZE		(72*1024)
#ifndef CONFIG_ARCH_M823V2
#define ERAM_MEMORY_SIZE		(640*1024)
#else
#define ERAM_MEMORY_SIZE		(320*1024)
#endif
#define SDRAM_MSP_MEMORY_SIZE		(16*1024*1024)

/* Host Interface */
#define COMCERTO_PHI_APB_FIFO_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0x0000)
#define COMCERTO_PHI_APB_FIFO_STATUS		APB_VADDR(COMCERTO_PHI_BASE + 0x0004)
#define COMCERTO_PHI_APB_FIFO_INTACK		APB_VADDR(COMCERTO_PHI_BASE + 0x0004)
#define COMCERTO_PHI_APB_BIST_CTRL_STAT		APB_VADDR(COMCERTO_PHI_BASE + 0x0008)
#define COMCERTO_PHI_APB_TX_FIFO_SIZE		APB_VADDR(COMCERTO_PHI_BASE + 0x0014)
#define COMCERTO_PHI_APB_TX_FIFO_HI_THRESH	APB_VADDR(COMCERTO_PHI_BASE + 0x0018)
#define COMCERTO_PHI_APB_TX_FIFO_LO_THRESH	APB_VADDR(COMCERTO_PHI_BASE + 0x001C)
#define COMCERTO_PHI_APB_RX_FIFO_SIZE		APB_VADDR(COMCERTO_PHI_BASE + 0x0024)
#define COMCERTO_PHI_APB_RX_FIFO_HI_THRESH	APB_VADDR(COMCERTO_PHI_BASE + 0x0028)
#define COMCERTO_PHI_APB_RX_FIFO_LO_THRESH	APB_VADDR(COMCERTO_PHI_BASE + 0x002C)
#define COMCERTO_PHI_TX_MAIL0			APB_VADDR(COMCERTO_PHI_BASE + 0x0030)
#define COMCERTO_PHI_TX_MAIL1			APB_VADDR(COMCERTO_PHI_BASE + 0x0034)
#define COMCERTO_PHI_TX_MAIL2			APB_VADDR(COMCERTO_PHI_BASE + 0x0038)
#define COMCERTO_PHI_TX_MAIL3			APB_VADDR(COMCERTO_PHI_BASE + 0x003C)
#define COMCERTO_PHI_RX_MAIL0			APB_VADDR(COMCERTO_PHI_BASE + 0x0040)
#define COMCERTO_PHI_RX_MAIL1			APB_VADDR(COMCERTO_PHI_BASE + 0x0044)
#define COMCERTO_PHI_RX_MAIL2			APB_VADDR(COMCERTO_PHI_BASE + 0x0048)
#define COMCERTO_PHI_RX_MAIL3			APB_VADDR(COMCERTO_PHI_BASE + 0x004C)
#define COMCERTO_PHI_PCI_IF_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0x0050)
#define COMCERTO_PHI_PCI_IF_STATUS		APB_VADDR(COMCERTO_PHI_BASE + 0x0054)
#define COMCERTO_PHI_BME_DMA_START_ADDR		APB_VADDR(COMCERTO_PHI_BASE + 0x0060)
#define COMCERTO_PHI_BME_DMA_BURST_SIZE		APB_VADDR(COMCERTO_PHI_BASE + 0x0064)
#define COMCERTO_PHI_BME_DMA_XFER_LEN		APB_VADDR(COMCERTO_PHI_BASE + 0x0068)

#define COMCERTO_PHI_APB_FIFO_DATA8		APB_VADDR(COMCERTO_PHI_BASE + 0x4000)
#define COMCERTO_PHI_APB_FIFO_DATA16		APB_VADDR(COMCERTO_PHI_BASE + 0x8000)
#define COMCERTO_PHI_APB_FIFO_DATA32		APB_VADDR(COMCERTO_PHI_BASE + 0xC000)

/* Host Memory Bridge */
#define COMCERTO_HMB_FIFO_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xD000)
#define COMCERTO_HMB_HCSM_BIST_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xD008)
#define COMCERTO_HMB_FIFO_DATA8			APB_VADDR(COMCERTO_PHI_BASE + 0xE000)
#define COMCERTO_HMB_FIFO_DATA16		APB_VADDR(COMCERTO_PHI_BASE + 0xE100)
#define COMCERTO_HMB_FIFO_DATA32		APB_VADDR(COMCERTO_PHI_BASE + 0xE200)

#define COMCERTO_HMB_STATE_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xF000)
#define COMCERTO_HMB_MODE_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xF004)
#define COMCERTO_HMB_STATUS			APB_VADDR(COMCERTO_PHI_BASE + 0xF008)
#define COMCERTO_HMB_INTACK			APB_VADDR(COMCERTO_PHI_BASE + 0xF008)
#define COMCERTO_HMB_INT_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xF00C)
#define COMCERTO_HMB_PCI_BASE_ADDR1		APB_VADDR(COMCERTO_PHI_BASE + 0xF010)
#define COMCERTO_HMB_SYS_BASE_ADDR1		APB_VADDR(COMCERTO_PHI_BASE + 0xF014)
#define COMCERTO_HMB_SIZE_MASK1			APB_VADDR(COMCERTO_PHI_BASE + 0xF018)
#define COMCERTO_HMB_PCI_BASE_ADDR2		APB_VADDR(COMCERTO_PHI_BASE + 0xF020)
#define COMCERTO_HMB_SYS_BASE_ADDR2		APB_VADDR(COMCERTO_PHI_BASE + 0xF024)
#define COMCERTO_HMB_SIZE_MASK2			APB_VADDR(COMCERTO_PHI_BASE + 0xF028)
#define COMCERTO_HMB_AX_FIFO_DEPTH		APB_VADDR(COMCERTO_PHI_BASE + 0xF030)
#define COMCERTO_HMB_AX_FIFO_DATA_ADDR		APB_VADDR(COMCERTO_PHI_BASE + 0xF034)
#define COMCERTO_HMB_AX_FIFO_DATA_LEN		APB_VADDR(COMCERTO_PHI_BASE + 0xF038)
#define COMCERTO_HMB_PCI_ARBITER_CONTROL	APB_VADDR(COMCERTO_PHI_BASE + 0xF040)

/* Arbiter */
#define COMCERTO_ARBITER_PRIORITY(base)		APB_VADDR((base) + 0x00)
#define COMCERTO_ARBITER_TC(base)		APB_VADDR((base) + 0x04)
#define COMCERTO_ARBITER_TCCR(base)		APB_VADDR((base) + 0x08)
#define COMCERTO_ARBITER_STATUS(base)		APB_VADDR((base) + 0x0C)
#define ARBITER_TCCR_REQTDMAEN			(1<<10)
#define ARBITER_TCCR_REQARM0EN			(1<<11)
#define ARBITER_TCCR_REQARM1EN			(1<<12)
#define ARBITER_TCCR_REQIDMAEN			(1<<13)

/* PLL */
#define COMCERTO_PLL_ARM			APB_VADDR(COMCERTO_PLL_BASE + 0x00)
#define COMCERTO_PLL_SPU			APB_VADDR(COMCERTO_PLL_BASE + 0x04)
#define COMCERTO_PLL_AMBA			APB_VADDR(COMCERTO_PLL_BASE + 0x08)

#define PLL_POWER				0x04000000      /* PLL power control */
#define PLL_BYPASS				0x02000000      /* PLL bypass */
#define PLL_MUXSEL				0x01000000      /* PLL clock source selection */
#define PLL_RESET				0x00800000      /* PLL reset */
#define PLL_CONTROL_MASK			0xFFC00000      /* PLL control mask */

#ifndef CONFIG_ARCH_M823V2

#define COMCERTO_PLL_SERDES			APB_VADDR(COMCERTO_PLL_BASE + 0x14)
#define PLL_SERDES_DISABLE			(1 << 8)
#define PLL_SERDES_SOURCE_PLL1_DIV_2		(1 << 9)

#else

#define COMCERTO_PLL_PHY0_REFCLK		APB_VADDR(COMCERTO_PLL_BASE + 0x14)
#define COMCERTO_PLL_PHY1_REFCLK		APB_VADDR(COMCERTO_PLL_BASE + 0x18)

#endif

/* UART */
#define COMCERTO_UART1_USR			APB_VADDR(COMCERTO_UART1_BASE + 0x7C)
#define COMCERTO_UART0_USR			APB_VADDR(COMCERTO_UART0_BASE + 0x7C)

/* SDC SDRAM Controller */
#define COMCERTO_SDC_SDRAM_CFG1			APB_VADDR(COMCERTO_SDC_BASE + 0x10)
#define COMCERTO_SDC_SDRAM_CFG2			APB_VADDR(COMCERTO_SDC_BASE + 0x14)
#define COMCERTO_SDC_SDRAM_REFRESH		APB_VADDR(COMCERTO_SDC_BASE + 0x18)
#define COMCERTO_SDC_SDRAM_POWERON		APB_VADDR(COMCERTO_SDC_BASE + 0x1C)
#define COMCERTO_SDC_VERSION			APB_VADDR(COMCERTO_SDC_BASE + 0x28)
#define COMCERTO_SDC_DEVICE_ID			APB_VADDR(COMCERTO_SDC_BASE + 0x2C)

#ifdef CONFIG_ARCH_M823V2
#define COMCERTO_SDC_SOFTINIT			APB_VADDR(COMCERTO_SDC_BASE + 0x78)
#define COMCERTO_SDC_MISC_CONFIG		APB_VADDR(COMCERTO_SDC_BASE + 0x7C)
#define COMCERTO_SDC_DLL_CONTROL		APB_VADDR(COMCERTO_SDC_BASE + 0x80)
#define COMCERTO_SDC_DLL_DQS_OFFSET		APB_VADDR(COMCERTO_SDC_BASE + 0x88)
#define COMCERTO_SDC_DLL_MANUAL			APB_VADDR(COMCERTO_SDC_BASE + 0x8C)
#endif

/* GPIO  */
#define COMCERTO_GPIO_OUTPUT			APB_VADDR(COMCERTO_GPIO_BASE + 0x00)
#define COMCERTO_GPIO_OUTPUT_ENABLE		APB_VADDR(COMCERTO_GPIO_BASE + 0x04)
#define COMCERTO_GPIO_RISING_EDGE_INT_ENABLE	APB_VADDR(COMCERTO_GPIO_BASE + 0x08)
#define COMCERTO_GPIO_FALLING_EDGE_INT_ENABLE	APB_VADDR(COMCERTO_GPIO_BASE + 0x0C)	/* if specific IRQ is set to '0' in COMCERTO_GPIO_LEVEL_INT_ENABLE */
#define COMCERTO_GPIO_LEVEL_INT_POLARITY	COMCERTO_GPIO_FALLING_EDGE_INT_ENABLE	/* if specific IRQ is set to '1' in COMCERTO_GPIO_LEVEL_INT_ENABLE */
#define COMCERTO_GPIO_INPUT			APB_VADDR(COMCERTO_GPIO_BASE + 0x10)
#define COMCERTO_GPIO_APB_WS			APB_VADDR(COMCERTO_GPIO_BASE + 0x14)
#define COMCERTO_GPIO_MUX_CONFIG		APB_VADDR(COMCERTO_GPIO_BASE + 0x18)
#define COMCERTO_GPIO_SYSTEM_CONFIG		APB_VADDR(COMCERTO_GPIO_BASE + 0x1C)
#define COMCERTO_GPIO_TDM_MUX_CONTROL		APB_VADDR(COMCERTO_GPIO_BASE + 0x28)
#define COMCERTO_GPIO_SPU_GPIO_SELECT		APB_VADDR(COMCERTO_GPIO_BASE + 0x2C)
#define COMCERTO_GPIO_ARM_ID			APB_VADDR(COMCERTO_GPIO_BASE + 0x30)
#define COMCERTO_GPIO_DDR_STTL_BUFFER_TYPE	APB_VADDR(COMCERTO_GPIO_BASE + 0x34)
#define COMCERTO_GPIO_LOCK			APB_VADDR(COMCERTO_GPIO_BASE + 0x38)
#define COMCERTO_GPIO_ARBITER_CONFIG		APB_VADDR(COMCERTO_GPIO_BASE + 0x3C)
#define COMCERTO_GPIO_MODE_AND_OE_STATUS	APB_VADDR(COMCERTO_GPIO_BASE + 0x40)
#define COMCERTO_GPIO_IOCTRL			APB_VADDR(COMCERTO_GPIO_BASE + 0x44)
#define COMCERTO_GPIO_SELFTEST			APB_VADDR(COMCERTO_GPIO_BASE + 0x48)
#define COMCERTO_GPIO_EFUSE			APB_VADDR(COMCERTO_GPIO_BASE + 0x4C)
#define COMCERTO_GPIO_LEVEL_INT_ENABLE		APB_VADDR(COMCERTO_GPIO_BASE + 0x50)
#define COMCERTO_GPIO_INT_STATUS		APB_VADDR(COMCERTO_GPIO_BASE + 0x54)
#define COMCERTO_GPIO_INT_MASK			APB_VADDR(COMCERTO_GPIO_BASE + 0x58)
#define COMCERTO_GPIO_WDT_GPIO_LINE_SELECT	APB_VADDR(COMCERTO_GPIO_BASE + 0x5C)

#define GPIO_IOCTRL_I2C				0
#define GPIO_IOCTRL_SPI0			4
#define GPIO_IOCTRL_GEMAC0			8
#define GPIO_IOCTRL_GEMAC1			10
#define GPIO_IOCTRL_UART0			12
#define GPIO_IOCTRL_UART1			14
#define GPIO_IOCTRL_UEXP			24
#define GPIO_IOCTRL_SPI1			28

/* Decoder */
#define COMCERTO_DECODER_CS0_MBA		APB_VADDR(COMCERTO_DECODER_BASE + 0x00)
#define COMCERTO_DECODER_CS1_MBA		APB_VADDR(COMCERTO_DECODER_BASE + 0x04)
#define COMCERTO_DECODER_CSE			APB_VADDR(COMCERTO_DECODER_BASE + 0x0C)
#define COMCERTO_DECODER_CS0_EXA		APB_VADDR(COMCERTO_DECODER_BASE + 0x10)
#define COMCERTO_DECODER_CS1_EXA		APB_VADDR(COMCERTO_DECODER_BASE + 0x14)
#define COMCERTO_DECODER_FCS_START		APB_VADDR(COMCERTO_DECODER_BASE + 0x30)
#define COMCERTO_DECODER_FCS_END		APB_VADDR(COMCERTO_DECODER_BASE + 0x34)

#define DECODER_CSE_CS0_ENABLE			(1 << 0)
#define DECODER_CSE_CS1_ENABLE			(1 << 1)
#define DECODER_CSE_CS2_ENABLE			(1 << 2)
#define DECODER_CSE_CS3_ENABLE			(1 << 3)
#define DECODER_CSE_ROM_REMAP_ENABLE		(1 << 4)
#define DECODER_CSE_CS4_ENABLE			(1 << 5)
#define DECODER_CSE_CS5_ENABLE			(1 << 6)
#define DECODER_CSE_HIGHMEM_SELECT		(1 << 7)

#define DECODER_CS0_EXA_INCLUDE_LOW_128MB	(1 << 7)

/* Timers  */
#define COMCERTO_TIMER0_HIGH_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x00)
#define COMCERTO_TIMER0_CURRENT_COUNT		APB_VADDR(COMCERTO_TIMER_BASE + 0x04)

#define COMCERTO_TIMER1_HIGH_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x08)
#define COMCERTO_TIMER1_CURRENT_COUNT		APB_VADDR(COMCERTO_TIMER_BASE + 0x0C)

#define COMCERTO_TIMER2_LOW_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x10)
#define COMCERTO_TIMER2_HIGH_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x14)
#define COMCERTO_TIMER2_CTRL			APB_VADDR(COMCERTO_TIMER_BASE + 0x18)
#define COMCERTO_TIMER2_CURRENT_COUNT		APB_VADDR(COMCERTO_TIMER_BASE + 0x1C)

#define COMCERTO_TIMER3_LOW_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x20)
#define COMCERTO_TIMER3_HIGH_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x24)
#define COMCERTO_TIMER3_CTRL			APB_VADDR(COMCERTO_TIMER_BASE + 0x28)
#define COMCERTO_TIMER3_CURRENT_COUNT		APB_VADDR(COMCERTO_TIMER_BASE + 0x2C)

#define COMCERTO_TIMER_IRQ_MASK			APB_VADDR(COMCERTO_TIMER_BASE + 0x40)
#define COMCERTO_TIMER_STATUS			APB_VADDR(COMCERTO_TIMER_BASE + 0x50)
#define COMCERTO_TIMER_STATUS_CLR		APB_VADDR(COMCERTO_TIMER_BASE + 0x50)

#define COMCERTO_TIMER_WDT_HIGH_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0xD0)
#define COMCERTO_TIMER_WDT_GPIO_PULSE_WIDTH	APB_VADDR(COMCERTO_TIMER_BASE + 0xD4)	/* bits 31:16 */
#define COMCERTO_TIMER_WDT_CONTROL		APB_VADDR(COMCERTO_TIMER_BASE + 0xD4)	/* bits 15:00 */
#define COMCERTO_TIMER_WDT_CURRENT_COUNT	APB_VADDR(COMCERTO_TIMER_BASE + 0xD8)

/* Interrupt Controller */
#define COMCERTO_INTC_STATUS0			APB_VADDR(COMCERTO_INTC_BASE + 0x00)
#define COMCERTO_INTC_SET_STATUS0		APB_VADDR(COMCERTO_INTC_BASE + 0x04)
#define COMCERTO_INTC_ARM0_IRQMASK0		APB_VADDR(COMCERTO_INTC_BASE + 0x08)
#define COMCERTO_INTC_ARM0_FIQMASK0		APB_VADDR(COMCERTO_INTC_BASE + 0x0C)
#define COMCERTO_INTC_ARM1_IRQMASK0		APB_VADDR(COMCERTO_INTC_BASE + 0x10)
#define COMCERTO_INTC_ARM1_FIQMASK0		APB_VADDR(COMCERTO_INTC_BASE + 0x14)
#define COMCERTO_INTC_ARM_CONTROL		APB_VADDR(COMCERTO_INTC_BASE + 0x18)

#define COMCERTO_INTC_STATUS1			APB_VADDR(COMCERTO_INTC_BASE + 0x20)
#define COMCERTO_INTC_SET_STATUS1		APB_VADDR(COMCERTO_INTC_BASE + 0x24)
#define COMCERTO_INTC_ARM0_IRQMASK1		APB_VADDR(COMCERTO_INTC_BASE + 0x28)
#define COMCERTO_INTC_ARM0_FIQMASK1		APB_VADDR(COMCERTO_INTC_BASE + 0x2C)
#define COMCERTO_INTC_ARM1_IRQMASK1		APB_VADDR(COMCERTO_INTC_BASE + 0x30)
#define COMCERTO_INTC_ARM1_FIQMASK1		APB_VADDR(COMCERTO_INTC_BASE + 0x34)

#define COMCERTO_INTC_ARM0_PRIORITY		APB_VADDR(COMCERTO_INTC_BASE + 0x40)
#define COMCERTO_INTC_ARM0_WINNER		APB_VADDR(COMCERTO_INTC_BASE + 0x60)
#define COMCERTO_INTC_SELF_CLEAR		APB_VADDR(COMCERTO_INTC_BASE + 0x64)
#define COMCERTO_INTC_ARM1_PRIORITY		APB_VADDR(COMCERTO_INTC_BASE + 0x80)
#define COMCERTO_INTC_ARM1_WINNER		APB_VADDR(COMCERTO_INTC_BASE + 0xA0)

/* Network Timing Generator */
#define COMCERTO_NTG_FREQ_SET_INT		APB_VADDR(COMCERTO_NTG_BASE + 0x00)
#define COMCERTO_NTG_FREQ_SET_FRA		APB_VADDR(COMCERTO_NTG_BASE + 0x04)
#define COMCERTO_NTG_PHASE_ADJ_FREQ_INT		APB_VADDR(COMCERTO_NTG_BASE + 0x10)
#define COMCERTO_NTG_PHASE_ADJ_FREQ_FRA		APB_VADDR(COMCERTO_NTG_BASE + 0x14)
#define COMCERTO_NTG_PHASE_ADJ_DUR		APB_VADDR(COMCERTO_NTG_BASE + 0x18)
#define COMCERTO_NTG_PHASE_ADJ_START		APB_VADDR(COMCERTO_NTG_BASE + 0x1C)
#define COMCERTO_NTG_MODE			APB_VADDR(COMCERTO_NTG_BASE + 0x20)
#define COMCERTO_NTG_PULSE_WIDTH		APB_VADDR(COMCERTO_NTG_BASE + 0x30)
#define COMCERTO_NTG_FRAME_LENGTH		APB_VADDR(COMCERTO_NTG_BASE + 0x34)
#define COMCERTO_NTG_PHASE_FRAME		APB_VADDR(COMCERTO_NTG_BASE + 0x38)
#define COMCERTO_NTG_FRAME_COUNT		APB_VADDR(COMCERTO_NTG_BASE + 0x3C)

/* MEMCORE */
#define COMCERTO_MEMCORE_MEM_CONFIG		APB_VADDR(COMCERTO_MEMCORE_BASE + 0x18)

/* Universal Expansion Bus, Direct Access registers */
#define COMCERTO_UEXP_DA_VADDR_BASE		0xFF000000
#define COMCERTO_UEXP_DA_VADDR(x)		((x) - COMCERTO_UEXP_DA_BASE + COMCERTO_UEXP_DA_VADDR_BASE)

#define COMCERTO_UEXP_DA_ENABLE			COMCERTO_UEXP_DA_VADDR(COMCERTO_UEXP_DA_BASE + 0x00)
#define COMCERTO_UEXP_DA_ADDRESS		COMCERTO_UEXP_DA_VADDR(COMCERTO_UEXP_DA_BASE + 0x04)
#define COMCERTO_UEXP_DA_WRITE			COMCERTO_UEXP_DA_VADDR(COMCERTO_UEXP_DA_BASE + 0x20)
#define COMCERTO_UEXP_DA_CONTROL		COMCERTO_UEXP_DA_VADDR(COMCERTO_UEXP_DA_BASE + 0x40)
#define COMCERTO_UEXP_DA_READ			COMCERTO_UEXP_DA_VADDR(COMCERTO_UEXP_DA_BASE + 0x60)

#define UEXP_DA_CONTROL_CLE			(1<<14)
#define UEXP_DA_CONTROL_ALE			(1<<15)

/* Universal Expansion Bus */
#define COMCERTO_UEXP_CS0_CFGA			APB_VADDR(COMCERTO_SDC_BASE + 0x00)
#define COMCERTO_UEXP_CS1_CFGA			APB_VADDR(COMCERTO_SDC_BASE + 0x04)
#define COMCERTO_UEXP_CS2_CFGA			APB_VADDR(COMCERTO_SDC_BASE + 0x08)
#define COMCERTO_UEXP_CS3_CFGA			APB_VADDR(COMCERTO_SDC_BASE + 0x0C)
#define COMCERTO_UEXP_CS4_CFGA			APB_VADDR(COMCERTO_SDC_BASE + 0x20)
#define COMCERTO_UEXP_CS5_CFGA			APB_VADDR(COMCERTO_SDC_BASE + 0x24)
#define COMCERTO_UEXP_CS0_CFGB			APB_VADDR(COMCERTO_SDC_BASE + 0x30)
#define COMCERTO_UEXP_CS1_CFGB			APB_VADDR(COMCERTO_SDC_BASE + 0x34)
#define COMCERTO_UEXP_CS2_CFGB			APB_VADDR(COMCERTO_SDC_BASE + 0x38)
#define COMCERTO_UEXP_CS3_CFGB			APB_VADDR(COMCERTO_SDC_BASE + 0x3C)
#define COMCERTO_UEXP_CS4_CFGB			APB_VADDR(COMCERTO_SDC_BASE + 0x40)
#define COMCERTO_UEXP_CS5_CFGB			APB_VADDR(COMCERTO_SDC_BASE + 0x44)
#define COMCERTO_UEXP_CS0_CFGC			APB_VADDR(COMCERTO_SDC_BASE + 0x50)
#define COMCERTO_UEXP_CS1_CFGC			APB_VADDR(COMCERTO_SDC_BASE + 0x54)
#define COMCERTO_UEXP_CS2_CFGC			APB_VADDR(COMCERTO_SDC_BASE + 0x58)
#define COMCERTO_UEXP_CS3_CFGC			APB_VADDR(COMCERTO_SDC_BASE + 0x5C)
#define COMCERTO_UEXP_CS4_CFGC			APB_VADDR(COMCERTO_SDC_BASE + 0x60)
#define COMCERTO_UEXP_CS5_CFGC			APB_VADDR(COMCERTO_SDC_BASE + 0x64)
#define COMCERTO_UEXP_CONFIG			APB_VADDR(COMCERTO_SDC_BASE + 0x70)

#define UEXP_CS0_CFGA_MEMCONTROLLER_SELECT	(1<<9)

#endif /* __ASM_ARCH_COMCERTO_300_H */
