/*
 *  linux/include/asm-arm/arch-comcerto/comcerto-515.h
 *
 *  Copyright (C) 2004,2005 Mindspeed Technologies, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
#ifndef __ASM_ARCH_COMCERTO_515_H
#define __ASM_ARCH_COMCERTO_515_H


/*
 * ========================================================================
 *  Comcerto definitions
 * ========================================================================
 *
 */

#define COMCERTO_CS5_BASE		0x11C00000
#define COMCERTO_CS4_BASE		0x11800000
#define COMCERTO_CS3_BASE		0x11400000
#define COMCERTO_CS2_BASE		0x11000000

#define COMCERTO_SDC1_BASE		0x101B0000
#define COMCERTO_MEMCORE_BASE		0x100F0000
#define COMCERTO_EDMA_EMAC0_BASE	0x100E0100
#define COMCERTO_IDMA_BASE		0x100E0000
#define COMCERTO_EMAC0_BASE		0x100D0000
#define COMCERTO_PLL_BASE		0x100B0000
#define COMCERTO_INTC_BASE		0x100A0000
#define COMCERTO_I2C_BASE		0x1009C000
#define COMCERTO_SPI0_BASE		0x10098000
#define COMCERTO_UART1_BASE		0x10094000
#define COMCERTO_UART0_BASE		0x10090000
#define COMCERTO_SDC_BASE		0x10080000
#define COMCERTO_GPIO_BASE		0x10070000
#define COMCERTO_DECODER_BASE		0x10060000
#define COMCERTO_TIMER_BASE		0x10050000
#define COMCERTO_ARBITER_ARAM_BASE	0x10048000
#define COMCERTO_ARBITER_BASE		0x10040000
#define COMCERTO_TDMA_BASE		0x10020000
#define COMCERTO_PHI_BASE		0x10010000

#define APB_MEMORY_PHY			0x10000000
#define ARAM_MEMORY_PHY			0x0A000000
#define IRAM_MEMORY_PHY			0x09000000
#define ERAM_MEMORY_PHY			0x08000000
#define SDRAM_MSP_MEMORY_PHY		0x00000000

#define APB_MEMORY_VADDR		0xE8000000
#define ARAM_MEMORY_VADDR		0xFA000000
#define IRAM_MEMORY_VADDR		0xF9000000
#define ERAM_MEMORY_VADDR		0xF8000000
#define SDRAM_MSP_MEMORY_VADDR		0xF0000000

#define APB_MEMORY_SIZE			(16*1024*1024)
#define ARAM_MEMORY_SIZE		(0*1024)
#define IRAM_MEMORY_SIZE		(8*1024)
#define ERAM_MEMORY_SIZE		(384*1024)
#define SDRAM_MSP_MEMORY_SIZE		(16*1024*1024)

/* Host Interface */
#define COMCERTO_PHI_APB_FIFO_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0x0000)
#define COMCERTO_PHI_APB_FIFO_STATUS		APB_VADDR(COMCERTO_PHI_BASE + 0x0004)
#define COMCERTO_PHI_APB_FIFO_INTACK		APB_VADDR(COMCERTO_PHI_BASE + 0x0004)
#define COMCERTO_PHI_APB_BIST_CTRL_STAT		APB_VADDR(COMCERTO_PHI_BASE + 0x0008)
#define COMCERTO_PHI_APB_TX_FIFO_SIZE		APB_VADDR(COMCERTO_PHI_BASE + 0x0014)
#define COMCERTO_PHI_APB_TX_FIFO_HI_THRESH	APB_VADDR(COMCERTO_PHI_BASE + 0x0018)
#define COMCERTO_PHI_APB_TX_FIFO_LO_THRESH	APB_VADDR(COMCERTO_PHI_BASE + 0x001C)
#define COMCERTO_PHI_APB_RX_FIFO_SIZE		APB_VADDR(COMCERTO_PHI_BASE + 0x0024)
#define COMCERTO_PHI_APB_RX_FIFO_HI_THRESH	APB_VADDR(COMCERTO_PHI_BASE + 0x0028)
#define COMCERTO_PHI_APB_RX_FIFO_LO_THRESH	APB_VADDR(COMCERTO_PHI_BASE + 0x002C)
#define COMCERTO_PHI_TX_MAIL0			APB_VADDR(COMCERTO_PHI_BASE + 0x0030)
#define COMCERTO_PHI_TX_MAIL1			APB_VADDR(COMCERTO_PHI_BASE + 0x0034)
#define COMCERTO_PHI_TX_MAIL2			APB_VADDR(COMCERTO_PHI_BASE + 0x0038)
#define COMCERTO_PHI_TX_MAIL3			APB_VADDR(COMCERTO_PHI_BASE + 0x003C)
#define COMCERTO_PHI_RX_MAIL0			APB_VADDR(COMCERTO_PHI_BASE + 0x0040)
#define COMCERTO_PHI_RX_MAIL1			APB_VADDR(COMCERTO_PHI_BASE + 0x0044)
#define COMCERTO_PHI_RX_MAIL2			APB_VADDR(COMCERTO_PHI_BASE + 0x0048)
#define COMCERTO_PHI_RX_MAIL3			APB_VADDR(COMCERTO_PHI_BASE + 0x004C)
#define COMCERTO_PHI_PCI_IF_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0x0050)
#define COMCERTO_PHI_PCI_IF_STATUS		APB_VADDR(COMCERTO_PHI_BASE + 0x0054)
#define COMCERTO_PHI_BME_DMA_START_ADDR		APB_VADDR(COMCERTO_PHI_BASE + 0x0060)
#define COMCERTO_PHI_BME_DMA_BURST_SIZE		APB_VADDR(COMCERTO_PHI_BASE + 0x0064)
#define COMCERTO_PHI_BME_DMA_XFER_LEN		APB_VADDR(COMCERTO_PHI_BASE + 0x0068)

#define COMCERTO_PHI_APB_FIFO_DATA8		APB_VADDR(COMCERTO_PHI_BASE + 0x4000)
#define COMCERTO_PHI_APB_FIFO_DATA16		APB_VADDR(COMCERTO_PHI_BASE + 0x8000)
#define COMCERTO_PHI_APB_FIFO_DATA32		APB_VADDR(COMCERTO_PHI_BASE + 0xC000)

/* Host Memory Bridge */
#define COMCERTO_HMB_FIFO_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xD000)
#define COMCERTO_HMB_HCSM_BIST_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xD008)
#define COMCERTO_HMB_FIFO_DATA8			APB_VADDR(COMCERTO_PHI_BASE + 0xE000)
#define COMCERTO_HMB_FIFO_DATA16		APB_VADDR(COMCERTO_PHI_BASE + 0xE100)
#define COMCERTO_HMB_FIFO_DATA32		APB_VADDR(COMCERTO_PHI_BASE + 0xE200)

#define COMCERTO_HMB_STATE_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xF000)
#define COMCERTO_HMB_MODE_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xF004)
#define COMCERTO_HMB_STATUS			APB_VADDR(COMCERTO_PHI_BASE + 0xF008)
#define COMCERTO_HMB_INTACK			APB_VADDR(COMCERTO_PHI_BASE + 0xF008)
#define COMCERTO_HMB_INT_CONTROL		APB_VADDR(COMCERTO_PHI_BASE + 0xF00C)
#define COMCERTO_HMB_PCI_BASE_ADDR1		APB_VADDR(COMCERTO_PHI_BASE + 0xF010)
#define COMCERTO_HMB_SYS_BASE_ADDR1		APB_VADDR(COMCERTO_PHI_BASE + 0xF014)
#define COMCERTO_HMB_SIZE_MASK1			APB_VADDR(COMCERTO_PHI_BASE + 0xF018)
#define COMCERTO_HMB_PCI_BASE_ADDR2		APB_VADDR(COMCERTO_PHI_BASE + 0xF020)
#define COMCERTO_HMB_SYS_BASE_ADDR2		APB_VADDR(COMCERTO_PHI_BASE + 0xF024)
#define COMCERTO_HMB_SIZE_MASK2			APB_VADDR(COMCERTO_PHI_BASE + 0xF028)
#define COMCERTO_HMB_AX_FIFO_DEPTH		APB_VADDR(COMCERTO_PHI_BASE + 0xF030)
#define COMCERTO_HMB_AX_FIFO_DATA_ADDR		APB_VADDR(COMCERTO_PHI_BASE + 0xF034)
#define COMCERTO_HMB_AX_FIFO_DATA_LEN		APB_VADDR(COMCERTO_PHI_BASE + 0xF038)
#define COMCERTO_HMB_PCI_ARBITER_CONTROL	APB_VADDR(COMCERTO_PHI_BASE + 0xF040)

/* Arbiter */
#define COMCERTO_ARBITER_PRIORITY(base)		APB_VADDR((base) + 0x00)
#define COMCERTO_ARBITER_TC(base)		APB_VADDR((base) + 0x04)
#define COMCERTO_ARBITER_TCCR(base)		APB_VADDR((base) + 0x08)
#define COMCERTO_ARBITER_STATUS(base)		APB_VADDR((base) + 0x0C)
#define ARBITER_TCCR_REQTDMAEN			(1<<10)
#define ARBITER_TCCR_REQARM0EN			(1<<11)
#define ARBITER_TCCR_REQARM1EN			(1<<12)
#define ARBITER_TCCR_REQIDMAEN			(1<<13)

/* PLL */
#define COMCERTO_PLL_ARM			APB_VADDR(COMCERTO_PLL_BASE + 0x00)
#define COMCERTO_PLL_SPU			APB_VADDR(COMCERTO_PLL_BASE + 0x04)
#define COMCERTO_PLL_AMBA			APB_VADDR(COMCERTO_PLL_BASE + 0x08)

/* SDC (SDRAM & SRAM interface) Control registers */
#define COMCERTO_SDC_CS0_CFG			APB_VADDR(COMCERTO_SDC_BASE + 0x00)
#define COMCERTO_SDC_CS1_CFG			APB_VADDR(COMCERTO_SDC_BASE + 0x04)
#define COMCERTO_SDC_CS2_CFG			APB_VADDR(COMCERTO_SDC_BASE + 0x08)
#define COMCERTO_SDC_CS3_CFG			APB_VADDR(COMCERTO_SDC_BASE + 0x0C)
#define COMCERTO_SDC_SDRAM_CFG1			APB_VADDR(COMCERTO_SDC_BASE + 0x10)
#define COMCERTO_SDC_SDRAM_CFG2			APB_VADDR(COMCERTO_SDC_BASE + 0x14)
#define COMCERTO_SDC_SDRAM_REFRESH		APB_VADDR(COMCERTO_SDC_BASE + 0x18)
#define COMCERTO_SDC_SDRAM_POWERON		APB_VADDR(COMCERTO_SDC_BASE + 0x1C)
#define COMCERTO_SDC_CS4_CFG			APB_VADDR(COMCERTO_SDC_BASE + 0x20)
#define COMCERTO_SDC_CS5_CFG			APB_VADDR(COMCERTO_SDC_BASE + 0x24)
#define COMCERTO_SDC_VERSION			APB_VADDR(COMCERTO_SDC_BASE + 0x28)
#define COMCERTO_SDC_DEVICE_ID			APB_VADDR(COMCERTO_SDC_BASE + 0x2C)

#define COMCERTO_SDC1_CS0_CFG			APB_VADDR(COMCERTO_SDC1_BASE + 0x00)
#define COMCERTO_SDC1_CS1_CFG			APB_VADDR(COMCERTO_SDC1_BASE + 0x04)
#define COMCERTO_SDC1_SDRAM_CFG1		APB_VADDR(COMCERTO_SDC1_BASE + 0x10)
#define COMCERTO_SDC1_SDRAM_CFG2		APB_VADDR(COMCERTO_SDC1_BASE + 0x14)
#define COMCERTO_SDC1_SDRAM_REFRESH		APB_VADDR(COMCERTO_SDC1_BASE + 0x18)
#define COMCERTO_SDC1_SDRAM_POWERON		APB_VADDR(COMCERTO_SDC1_BASE + 0x1C)

/* GPIO  */
#define COMCERTO_GPIO_OUTPUT			APB_VADDR(COMCERTO_GPIO_BASE + 0x00)
#define COMCERTO_GPIO_OUTPUT_ENABLE		APB_VADDR(COMCERTO_GPIO_BASE + 0x04)
#define COMCERTO_GPIO_RISING_EDGE_INT_ENABLE	APB_VADDR(COMCERTO_GPIO_BASE + 0x08)
#define COMCERTO_GPIO_FALLING_EDGE_INT_ENABLE	APB_VADDR(COMCERTO_GPIO_BASE + 0x0C)
#define COMCERTO_GPIO_INPUT			APB_VADDR(COMCERTO_GPIO_BASE + 0x10)
#define COMCERTO_GPIO_APB_WS			APB_VADDR(COMCERTO_GPIO_BASE + 0x14)
#define COMCERTO_GPIO_SYSTEM_CONFIG		APB_VADDR(COMCERTO_GPIO_BASE + 0x1C)
#define COMCERTO_GPIO_LOCK			APB_VADDR(COMCERTO_GPIO_BASE + 0x38)
#define COMCERTO_GPIO_IOCTRL			APB_VADDR(COMCERTO_GPIO_BASE + 0x44)

/* Decoder */
#define COMCERTO_DECODER_CS0_MBA		APB_VADDR(COMCERTO_DECODER_BASE + 0x00)
#define COMCERTO_DECODER_CS1_MBA		APB_VADDR(COMCERTO_DECODER_BASE + 0x04)
#define COMCERTO_DECODER_CSE			APB_VADDR(COMCERTO_DECODER_BASE + 0x0C)
#define COMCERTO_DECODER_CS0_EXA		APB_VADDR(COMCERTO_DECODER_BASE + 0x10)
#define COMCERTO_DECODER_CS1_EXA		APB_VADDR(COMCERTO_DECODER_BASE + 0x14)
#define COMCERTO_DECODER_SDC1_CS0_MBA		APB_VADDR(COMCERTO_DECODER_BASE + 0x18)
#define COMCERTO_DECODER_SDC1_CS1_MBA		APB_VADDR(COMCERTO_DECODER_BASE + 0x1C)
#define COMCERTO_DECODER_SDC1_CS0_EXA		APB_VADDR(COMCERTO_DECODER_BASE + 0x20)
#define COMCERTO_DECODER_SDC1_CS1_EXA		APB_VADDR(COMCERTO_DECODER_BASE + 0x24)
#define COMCERTO_DECODER_MEM_DIVIDER		APB_VADDR(COMCERTO_DECODER_BASE + 0x28)

#define DECODER_CSE_CS0_ENABLE			(1 << 0)
#define DECODER_CSE_CS1_ENABLE			(1 << 1)
#define DECODER_CSE_CS2_ENABLE			(1 << 2)
#define DECODER_CSE_CS3_ENABLE			(1 << 3)
#define DECODER_CSE_ROM_REMAP_ENABLE		(1 << 4)
#define DECODER_CSE_CS4_ENABLE			(1 << 5)
#define DECODER_CSE_CS5_ENABLE			(1 << 6)
#define DECODER_CSE_HIGHMEM_SELECT		(1 << 7)

/* Decoder registers */
#define ASD_MBA_EXP_CSSD0			APB_VADDR(COMCERTO_ASD_BASE + 0x00)
#define ASD_MBA_EXP_CSSD1			APB_VADDR(COMCERTO_ASD_BASE + 0x04)
#define ASD_CSE					APB_VADDR(COMCERTO_ASD_BASE + 0x0C)
#define ASD_EXA_EXP_CSSD0			APB_VADDR(COMCERTO_ASD_BASE + 0x10)
#define ASD_EXA_EXP_CSSD1			APB_VADDR(COMCERTO_ASD_BASE + 0x14)
#define ASD_MBA_SDR_CSSD0			APB_VADDR(COMCERTO_ASD_BASE + 0x18)
#define ASD_MBA_SDR_CSSD1			APB_VADDR(COMCERTO_ASD_BASE + 0x1C)
#define ASD_EXA_SDR_CSSD0			APB_VADDR(COMCERTO_ASD_BASE + 0x20)
#define ASD_EXA_SDR_CSSD1			APB_VADDR(COMCERTO_ASD_BASE + 0x24)
#define ASD_MEM_DIVIDER				APB_VADDR(COMCERTO_ASD_BASE + 0x28)

/* Timers  */
#define COMCERTO_TIMER0_HIGH_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x00)
#define COMCERTO_TIMER0_CURRENT_COUNT		APB_VADDR(COMCERTO_TIMER_BASE + 0x04)

#define COMCERTO_TIMER1_HIGH_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x08)
#define COMCERTO_TIMER1_CURRENT_COUNT		APB_VADDR(COMCERTO_TIMER_BASE + 0x0C)

#define COMCERTO_TIMER2_LOW_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x10)
#define COMCERTO_TIMER2_HIGH_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x14)
#define COMCERTO_TIMER2_CTRL			APB_VADDR(COMCERTO_TIMER_BASE + 0x18)
#define COMCERTO_TIMER2_CURRENT_COUNT		APB_VADDR(COMCERTO_TIMER_BASE + 0x1C)

#define COMCERTO_TIMER3_LOW_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x20)
#define COMCERTO_TIMER3_HIGH_BOUND		APB_VADDR(COMCERTO_TIMER_BASE + 0x24)
#define COMCERTO_TIMER3_CTRL			APB_VADDR(COMCERTO_TIMER_BASE + 0x28)
#define COMCERTO_TIMER3_CURRENT_COUNT		APB_VADDR(COMCERTO_TIMER_BASE + 0x2C)

#define COMCERTO_TIMER_IRQ_MASK			APB_VADDR(COMCERTO_TIMER_BASE + 0x40)
#define COMCERTO_TIMER_STATUS			APB_VADDR(COMCERTO_TIMER_BASE + 0x50)
#define COMCERTO_TIMER_STATUS_CLR		APB_VADDR(COMCERTO_TIMER_BASE + 0x50)

/* Interrupt Controller */
#define COMCERTO_INTC_STATUS0			APB_VADDR(COMCERTO_INTC_BASE + 0x00)
#define COMCERTO_INTC_SET_STATUS0		APB_VADDR(COMCERTO_INTC_BASE + 0x04)
#define COMCERTO_INTC_ARM0_IRQMASK0		APB_VADDR(COMCERTO_INTC_BASE + 0x08)
#define COMCERTO_INTC_ARM0_FIQMASK0		APB_VADDR(COMCERTO_INTC_BASE + 0x0C)
#define COMCERTO_INTC_ARM1_IRQMASK0		APB_VADDR(COMCERTO_INTC_BASE + 0x10)
#define COMCERTO_INTC_ARM1_FIQMASK0		APB_VADDR(COMCERTO_INTC_BASE + 0x14)
#define COMCERTO_INTC_ARM_CONTROL		APB_VADDR(COMCERTO_INTC_BASE + 0x18)

#define COMCERTO_INTC_STATUS1			APB_VADDR(COMCERTO_INTC_BASE + 0x20)
#define COMCERTO_INTC_SET_STATUS1		APB_VADDR(COMCERTO_INTC_BASE + 0x24)
#define COMCERTO_INTC_ARM0_IRQMASK1		APB_VADDR(COMCERTO_INTC_BASE + 0x28)
#define COMCERTO_INTC_ARM0_FIQMASK1		APB_VADDR(COMCERTO_INTC_BASE + 0x2C)
#define COMCERTO_INTC_ARM1_IRQMASK1		APB_VADDR(COMCERTO_INTC_BASE + 0x30)
#define COMCERTO_INTC_ARM1_FIQMASK1		APB_VADDR(COMCERTO_INTC_BASE + 0x34)

#define COMCERTO_INTC_ARM0_PRIORITY		APB_VADDR(COMCERTO_INTC_BASE + 0x40)
#define COMCERTO_INTC_ARM0_WINNER		APB_VADDR(COMCERTO_INTC_BASE + 0x60)
#define COMCERTO_INTC_SELF_CLEAR		APB_VADDR(COMCERTO_INTC_BASE + 0x64)
#define COMCERTO_INTC_ARM1_PRIORITY		APB_VADDR(COMCERTO_INTC_BASE + 0x80)
#define COMCERTO_INTC_ARM1_WINNER		APB_VADDR(COMCERTO_INTC_BASE + 0xA0)


#define COMCERTO_MEMCORE_MEM_CONFIG		APB_VADDR(COMCERTO_MEMCORE_BASE + 0x68)

#endif /* __ASM_ARCH_COMCERTO_515_H */
